language: python
python:
  - "3.8"
before_install:
  - export LOG_LEVEL=DEBUG
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
  - pytest --cov -v
after_success:
  - coveralls
